name: Build Rockbox Simulators

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:

jobs:

  bootstrap:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set-targets.outputs.targets }}
    steps:
      - name: Set targets
        id: set-targets
        run: |
          cat << 'EOF' > targets.json
          [
            {"name": "Apple iPod Color/Photo": "id: 20},
            {"name": "Apple iPod Nano 1G": "id: 21},
            {"name": "Apple iPod 3G", "id": 23},
            {"name": "Apple iPod 4G Grayscale", "id": 24},
            {"name": "Apple iPod Mini 2G", "id": 26},
            {"name": "Apple iPod Classic/6G", "id": 29},
            {"name": "Eros Q / K native", "id": 247}
          ]
          EOF
          echo "targets=$(cat targets.json | jq -c .)" >> $GITHUB_OUTPUT

  build-sdl2-win32:
    runs-on: ubuntu-latest
    steps:
      - name: Cache SDL2
        id: cache-sdl2
        uses: actions/cache@v4
        with:
          path: ~/mingw32-sdl
          key: sdl2-mingw-w64

      - name: Install dependencies
        if: steps.cache-sdl2.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64

      - name: Compile SDL2
        if: steps.cache-sdl2.outputs.cache-hit != 'true'
        run: |
          wget https://www.libsdl.org/release/SDL2-2.32.8.tar.gz
          tar xvzf SDL2-2.32.8.tar.gz
          cd SDL2-2.32.8
          ./configure --host=i686-w64-mingw32 --prefix=${HOME}/mingw32-sdl
          make && make install

  build-simulator-linux:
    runs-on: ubuntu-latest
    needs:
      - bootstrap
    outputs:
      hash: ${{ steps.build-info.outputs.hash }}
      date: ${{ steps.build-info.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.bootstrap.outputs.targets) }}

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl-dev

      - name: Clone Rockbox
        run: git clone git://git.rockbox.org/rockbox

      - name: Dump target IDs
        run: ./rockbox/tools/configure --type=s || true

      - name: Get build info
        id: build-info
        env:
          TARGET_ID: ${{ matrix.target.id }}
          TARGET_NAME: ${{ matrix.target.name }}
        run: |
          TARGET_SLUG=$(echo "${TARGET_NAME}" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/-\+/-/g' | tr '[:upper:]' '[:lower:]')
          HASH=$(git -C rockbox rev-parse --short HEAD)
          DATE=$(git -C rockbox log -1 --format=%cd --date=format:'%Y%m%d-%H%M%S')
          echo "hash=${HASH}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "folder_name=rockboxui-linux-${TARGET_SLUG}-${TARGET_ID}-${DATE}-${HASH}" >> $GITHUB_OUTPUT

      - name: Configure
        env:
          TARGET_ID: ${{ matrix.target.id }}
        run: ./rockbox/tools/configure --type=s --target="${TARGET_ID}"

      - name: Build
        run: |
          make
          make fullinstall

      - name: Upload simulator binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-info.outputs.folder_name }}
          path: |
            rockboxui
            simdisk/
            *.bmp
          if-no-files-found: 'error'
          retention-days: 7
          include-hidden-files: true # simdisk dir contains .rockbox folder

  build-simulator-win32:
    runs-on: ubuntu-latest
    needs:
      - bootstrap
      - build-sdl2-win32
    outputs:
      hash: ${{ steps.build-info.outputs.hash }}
      date: ${{ steps.build-info.outputs.date }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.bootstrap.outputs.targets) }}

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64

      - name: Restore SDL2 from cache
        uses: actions/cache@v4
        with:
          path: ~/mingw32-sdl
          key: sdl2-mingw-w64
          fail-on-cache-miss: true

      - name: Add SDL2 to PATH
        run: echo "${HOME}/mingw32-sdl/bin" >> $GITHUB_PATH

      - name: Clone Rockbox
        run: git clone git://git.rockbox.org/rockbox

      - name: Get build info
        id: build-info
        env:
          TARGET_ID: ${{ matrix.target.id }}
          TARGET_NAME: ${{ matrix.target.name }}
        run: |
          TARGET_SLUG=$(echo "${TARGET_NAME}" | sed 's/[^a-zA-Z0-9]/-/g' | sed 's/-\+/-/g' | tr '[:upper:]' '[:lower:]')
          HASH=$(git -C rockbox rev-parse --short HEAD)
          DATE=$(git -C rockbox log -1 --format=%cd --date=format:'%Y%m%d-%H%M%S')
          echo "hash=${HASH}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "folder_name=rockboxui-win32-${TARGET_SLUG}-${TARGET_ID}-${DATE}-${HASH}" >> $GITHUB_OUTPUT

      - name: Configure
        env:
          TARGET_ID: ${{ matrix.target.id }}
        run: ./rockbox/tools/configure --type=aSW --target="${TARGET_ID}"

      - name: Build
        run: |
          make
          make fullinstall

      - name: Upload simulator binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-info.outputs.folder_name }}
          path: |
            rockboxui.exe
            simdisk/
            *.bmp
          if-no-files-found: 'error'
          retention-days: 7
          include-hidden-files: true # simdisk dir contains .rockbox folder

  create-release:
    needs:
     - build-simulator-linux
     - build-simulator-win32
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download simulator artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip simulator artifacts
        run: |
          mkdir -p simulators
          cd artifacts
          for dir in */; do
            folder_name=$(basename "$dir")
            zip -r ../simulators/"${folder_name}.zip" "$dir"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2.5.0
        #if: github.ref == 'refs/heads/main'
        with:
          tag_name: rb-master
          name: rockbox simulator ${{ needs.build-simulator-linux.outputs.date }} ${{ needs.build-simulator-linux.outputs.hash }}
          files: simulators/*
          body: |
            [Rockbox](https://rockbox.org) [simulator](https://www.rockbox.org/wiki/UiSimulator.html) builds for linux.

            Built from commit [${{ needs.build-simulator-linux.outputs.hash }}](https://github.com/Rockbox/rockbox/commit/${{ needs.build-simulator-linux.outputs.hash }}) published on ${{ needs.build-simulator-linux.outputs.date }}.

            See assets for simulator binaries.
          generate_release_notes: false